import Layout from "../../components/Layout";
import { Text, Stack, useColorModeValue } from "@chakra-ui/react";
import { Head } from "../../components/seo/Head";
import Cta from "../../components/mnemonic/Cta";
import { ColorfulText, H1, H2, P } from "../../components/basics";

export default () => {
    return (
        <Layout>
            <Head
                title="Interweb ID | Why Mnemonics?"
                description="Why Mnemonics?"
                route="/mnemonic/about" />
            <Stack
                alignItems="center"
                justifyContent="center"
                textAlign="center"
                spacing={{ base: 5, md: 6 }}
            >
                <H1>
                    Embrace Mnemonics as Your Identity&nbsp;
                    <ColorfulText>
                        in the Web3 World
                    </ColorfulText>
                </H1>
                <H2>
                    The Power of Mnemonics in the Decentralized Web
                </H2>
                <P>
                    In the emerging era of Web3, where decentralized technologies and blockchain networks are reshaping the digital landscape, mnemonics are emerging as a powerful and innovative way to establish a unique and secure digital identity. Unlike traditional centralized systems that rely on usernames and passwords, mnemonics offer a more robust and self-sovereign approach to identity management.
                </P>
                <H2>
                    What are Mnemonics?
                </H2>

                <P>
                    Mnemonics, also known as mnemonic phrases or seed phrases, are sequences of words generated by cryptographic algorithms. Typically consisting of 12 to 24 words, mnemonics serve as a human-readable representation of complex cryptographic keys. These keys act as access points to various blockchain-based services, granting secure control over digital assets, managing decentralized identities, and executing smart contracts.
                </P>
                <H2>
                    So what does Identity have to do with Mnemonics?
                </H2>

                <P>
                    In the world of cryptography and decentralized technologies, the relationship between identity and mnemonics is a fundamental and transformative one. Mnemonics, those powerful cryptographic phrases, serve as the gateway to a self-sovereign digital identity. By generating unique mnemonic phrases, users gain control over their digital presence, managing access to their sensitive information and digital assets. Mnemonics become the keys to the castle, empowering individuals to traverse the decentralized landscape with confidence and privacy. As decentralized platforms continue to reshape the concept of digital identity, mnemonics stand tall as the emblem of self-determination and the guardian of personal data in the ever-evolving Web3 era.
                </P>
            </Stack>
            <Cta />

        </Layout>
    );
};
